// Code generated by MockGen. DO NOT EDIT.
// Source: C:\Users\ddovwll\GolandProjects\PrService\src\internal\domain\repositories.go
//
// Generated by this command:
//
//	mockgen -source=C:\Users\ddovwll\GolandProjects\PrService\src\internal\domain\repositories.go -package=mocks -destination=C:\Users\ddovwll\GolandProjects\PrService\src\internal\application\mocks\repositories_mock.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "PrService/src/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTeamRepository is a mock of TeamRepository interface.
type MockTeamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRepositoryMockRecorder
	isgomock struct{}
}

// MockTeamRepositoryMockRecorder is the mock recorder for MockTeamRepository.
type MockTeamRepositoryMockRecorder struct {
	mock *MockTeamRepository
}

// NewMockTeamRepository creates a new mock instance.
func NewMockTeamRepository(ctrl *gomock.Controller) *MockTeamRepository {
	mock := &MockTeamRepository{ctrl: ctrl}
	mock.recorder = &MockTeamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRepository) EXPECT() *MockTeamRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTeamRepository) Create(ctx context.Context, name domain.TeamName) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTeamRepositoryMockRecorder) Create(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamRepository)(nil).Create), ctx, name)
}

// GetByName mocks base method.
func (m *MockTeamRepository) GetByName(ctx context.Context, name domain.TeamName) (*domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockTeamRepositoryMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockTeamRepository)(nil).GetByName), ctx, name)
}

// GetByUserID mocks base method.
func (m *MockTeamRepository) GetByUserID(ctx context.Context, userID domain.UserID) (*domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockTeamRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockTeamRepository)(nil).GetByUserID), ctx, userID)
}

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserRepository) GetByID(ctx context.Context, id domain.UserID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepository)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockUserRepository) Update(ctx context.Context, user *domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepositoryMockRecorder) Update(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepository)(nil).Update), ctx, user)
}

// UpsertBatch mocks base method.
func (m *MockUserRepository) UpsertBatch(ctx context.Context, users []domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertBatch", ctx, users)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertBatch indicates an expected call of UpsertBatch.
func (mr *MockUserRepositoryMockRecorder) UpsertBatch(ctx, users any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertBatch", reflect.TypeOf((*MockUserRepository)(nil).UpsertBatch), ctx, users)
}

// MockPullRequestRepository is a mock of PullRequestRepository interface.
type MockPullRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockPullRequestRepositoryMockRecorder is the mock recorder for MockPullRequestRepository.
type MockPullRequestRepositoryMockRecorder struct {
	mock *MockPullRequestRepository
}

// NewMockPullRequestRepository creates a new mock instance.
func NewMockPullRequestRepository(ctrl *gomock.Controller) *MockPullRequestRepository {
	mock := &MockPullRequestRepository{ctrl: ctrl}
	mock.recorder = &MockPullRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestRepository) EXPECT() *MockPullRequestRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPullRequestRepository) Create(ctx context.Context, pr *domain.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPullRequestRepositoryMockRecorder) Create(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPullRequestRepository)(nil).Create), ctx, pr)
}

// GetByID mocks base method.
func (m *MockPullRequestRepository) GetByID(ctx context.Context, id domain.PullRequestID) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPullRequestRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPullRequestRepository)(nil).GetByID), ctx, id)
}

// ListByReviewer mocks base method.
func (m *MockPullRequestRepository) ListByReviewer(ctx context.Context, reviewerID domain.UserID) ([]domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByReviewer", ctx, reviewerID)
	ret0, _ := ret[0].([]domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByReviewer indicates an expected call of ListByReviewer.
func (mr *MockPullRequestRepositoryMockRecorder) ListByReviewer(ctx, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByReviewer", reflect.TypeOf((*MockPullRequestRepository)(nil).ListByReviewer), ctx, reviewerID)
}

// Update mocks base method.
func (m *MockPullRequestRepository) Update(ctx context.Context, pr *domain.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPullRequestRepositoryMockRecorder) Update(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPullRequestRepository)(nil).Update), ctx, pr)
}
