// Code generated by MockGen. DO NOT EDIT.
// Source: src/internal/domain/services.go
//
// Generated by this command:
//
//	mockgen -source=src/internal/domain/services.go -package=mocks -destination=src/internal/http_api/mocks/services_mock.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "PrService/src/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPullRequestService is a mock of PullRequestService interface.
type MockPullRequestService struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestServiceMockRecorder
	isgomock struct{}
}

// MockPullRequestServiceMockRecorder is the mock recorder for MockPullRequestService.
type MockPullRequestServiceMockRecorder struct {
	mock *MockPullRequestService
}

// NewMockPullRequestService creates a new mock instance.
func NewMockPullRequestService(ctrl *gomock.Controller) *MockPullRequestService {
	mock := &MockPullRequestService{ctrl: ctrl}
	mock.recorder = &MockPullRequestServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestService) EXPECT() *MockPullRequestServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPullRequestService) Create(ctx context.Context, id domain.PullRequestID, pullRequestName string, userID domain.UserID) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, id, pullRequestName, userID)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPullRequestServiceMockRecorder) Create(ctx, id, pullRequestName, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPullRequestService)(nil).Create), ctx, id, pullRequestName, userID)
}

// Merge mocks base method.
func (m *MockPullRequestService) Merge(ctx context.Context, id domain.PullRequestID) (*domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", ctx, id)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Merge indicates an expected call of Merge.
func (mr *MockPullRequestServiceMockRecorder) Merge(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockPullRequestService)(nil).Merge), ctx, id)
}

// Reassign mocks base method.
func (m *MockPullRequestService) Reassign(ctx context.Context, id domain.PullRequestID, oldRevID domain.UserID) (*domain.PullRequest, domain.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reassign", ctx, id, oldRevID)
	ret0, _ := ret[0].(*domain.PullRequest)
	ret1, _ := ret[1].(domain.UserID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Reassign indicates an expected call of Reassign.
func (mr *MockPullRequestServiceMockRecorder) Reassign(ctx, id, oldRevID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reassign", reflect.TypeOf((*MockPullRequestService)(nil).Reassign), ctx, id, oldRevID)
}

// MockTeamService is a mock of TeamService interface.
type MockTeamService struct {
	ctrl     *gomock.Controller
	recorder *MockTeamServiceMockRecorder
	isgomock struct{}
}

// MockTeamServiceMockRecorder is the mock recorder for MockTeamService.
type MockTeamServiceMockRecorder struct {
	mock *MockTeamService
}

// NewMockTeamService creates a new mock instance.
func NewMockTeamService(ctrl *gomock.Controller) *MockTeamService {
	mock := &MockTeamService{ctrl: ctrl}
	mock.recorder = &MockTeamServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamService) EXPECT() *MockTeamServiceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTeamService) Create(ctx context.Context, team *domain.Team) (*domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, team)
	ret0, _ := ret[0].(*domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTeamServiceMockRecorder) Create(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTeamService)(nil).Create), ctx, team)
}

// Get mocks base method.
func (m *MockTeamService) Get(ctx context.Context, name domain.TeamName) (*domain.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name)
	ret0, _ := ret[0].(*domain.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTeamServiceMockRecorder) Get(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTeamService)(nil).Get), ctx, name)
}

// GetStats mocks base method.
func (m *MockTeamService) GetStats(ctx context.Context, name domain.TeamName) (*domain.TeamStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStats", ctx, name)
	ret0, _ := ret[0].(*domain.TeamStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStats indicates an expected call of GetStats.
func (mr *MockTeamServiceMockRecorder) GetStats(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStats", reflect.TypeOf((*MockTeamService)(nil).GetStats), ctx, name)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// GetPrs mocks base method.
func (m *MockUserService) GetPrs(ctx context.Context, userID domain.UserID) ([]domain.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrs", ctx, userID)
	ret0, _ := ret[0].([]domain.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrs indicates an expected call of GetPrs.
func (mr *MockUserServiceMockRecorder) GetPrs(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrs", reflect.TypeOf((*MockUserService)(nil).GetPrs), ctx, userID)
}

// SetIsActive mocks base method.
func (m *MockUserService) SetIsActive(ctx context.Context, userID domain.UserID, isActive bool) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetIsActive", ctx, userID, isActive)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetIsActive indicates an expected call of SetIsActive.
func (mr *MockUserServiceMockRecorder) SetIsActive(ctx, userID, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetIsActive", reflect.TypeOf((*MockUserService)(nil).SetIsActive), ctx, userID, isActive)
}
